# Generated by Django 4.2.5 on 2023-10-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion_model',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion_model',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
    ]
