# Generated by Django 4.2.5 on 2023-10-18 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0004_comentarios_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion_model',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
