# Generated by Django 4.2.5 on 2023-10-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0005_alter_publicacion_model_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion_model',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
