# Generated by Django 4.2.5 on 2023-10-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='images/user'),
        ),
    ]
