# Generated by Django 4.2.5 on 2023-10-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0003_alter_avatar_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='imagen',
            new_name='avatar',
        ),
    ]
