# Generated by Django 4.2.5 on 2023-10-19 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0004_rename_imagen_avatar_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avatar',
            name='social1',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avatar',
            name='social2',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
